sudo: required
services:
  - docker
script:
  - docker build -t mylabcloud .
after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - docker tag mylabcloud $DOCKER_USER/masterlemoncode_cloud
  - docker push $DOCKER_USER/masterlemoncode_cloud
