sudo: required
services:
  - docker
script:
  - docker build -t labcloud .
after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - docker tag labcloud $DOCKER_USER/masterlemoncode_cloud
  - docker push $DOCKER_USER/masterlemoncode_cloud
deploy:
  provider: script
  skip_cleanup: true
  script: ssh -i $KEY ec2-user@$HOST 'bash ./deploy.sh'
