sudo: required
services:
  - docker
script:
  - docker build -t labcloud .
after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - docker tag labcloud $DOCKER_USER/masterlemoncode_cloud
  - docker push $DOCKER_USER/masterlemoncode_cloud
before_deploy:
  - sudo openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: sudo ssh -i /tmp/deploy_rsa ec2-user@ec2-63-32-112-235.eu-west-1.compute.amazonaws.com 'bash ./deploy.sh'
  on:
    branch: master
